### ISSUE TITLE
Milestone 2 Issue

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#86]
- [x] `results/confidence-interval-estimate-table.csv` is not fed into the report in the Makefile. Was this intended?

**Comment by hfboyce** [comment]
@aimirza 

Yes! We made the table thinking we were going to use it in our report but ended up not including it for simplicity and to avoid redundancy. I asked Tiffany and she said instead of deleting the code, simply keep the additional file outputs for extra information since we have it. The same goes for the histograms png.
